Fix build error due to missing include
Error was:

  platform/common/mp3.c:11:10: fatal error: pico/pico_int.h: No such file or directory
     11 | #include <pico/pico_int.h>
        |          ^~~~~~~~~~~~~~~~~